version: 2
jobs:
  build:
    working_directory: ~/awesome-stars
    docker:
      - image: circleci/node:6.10.3
    steps:
      - checkout
      - run:
          name: install-gulp
          command: sudo npm install gulp --global
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ] || [ "${CIRCLE_BRANCH}" == "master" ]; then
              gulp build --production --vendor=chrome
              gulp pack --vendor=chrome
            fi
      - store_artifacts:
          path: packages
          prefix: packages
